// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpZ1rz_CTpX_FF7wQg3_KAiYAV4Ui05RM',
    appId: '1:794963713226:web:9b67d69d271f88ef50a833',
    messagingSenderId: '794963713226',
    projectId: 'connectapp-68736',
    authDomain: 'connectapp-68736.firebaseapp.com',
    storageBucket: 'connectapp-68736.appspot.com',
    measurementId: 'G-X9X9JNY9JX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpPbmAa_n2g2S4BCnVUcIfwQWOZHB6C5o',
    appId: '1:794963713226:android:a6d11af49b1dcae750a833',
    messagingSenderId: '794963713226',
    projectId: 'connectapp-68736',
    storageBucket: 'connectapp-68736.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDL-0QIGN_eJ-kKcGOot4HJaLJ_4gV_u_s',
    appId: '1:794963713226:ios:b00bab5c048aeca750a833',
    messagingSenderId: '794963713226',
    projectId: 'connectapp-68736',
    storageBucket: 'connectapp-68736.appspot.com',
    iosBundleId: 'com.example.connectApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDL-0QIGN_eJ-kKcGOot4HJaLJ_4gV_u_s',
    appId: '1:794963713226:ios:330bb82b1a3631b350a833',
    messagingSenderId: '794963713226',
    projectId: 'connectapp-68736',
    storageBucket: 'connectapp-68736.appspot.com',
    iosBundleId: 'com.example.connectApp.RunnerTests',
  );
}
